/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthUpdatesRouteImport } from './routes/_auth/updates'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthSearchRouteImport } from './routes/_auth/search'
import { Route as AuthDiscoverRouteImport } from './routes/_auth/discover'
import { Route as AuthActivityRouteImport } from './routes/_auth/activity'
import { Route as AuthGamePlatformSlugRouteImport } from './routes/_auth/game.$platform.$slug'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUpdatesRoute = AuthUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSearchRoute = AuthSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDiscoverRoute = AuthDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthRoute,
} as any)
const AuthActivityRoute = AuthActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGamePlatformSlugRoute = AuthGamePlatformSlugRouteImport.update({
  id: '/game/$platform/$slug',
  path: '/game/$platform/$slug',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AuthActivityRoute
  '/discover': typeof AuthDiscoverRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/updates': typeof AuthUpdatesRoute
  '/game/$platform/$slug': typeof AuthGamePlatformSlugRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/activity': typeof AuthActivityRoute
  '/discover': typeof AuthDiscoverRoute
  '/search': typeof AuthSearchRoute
  '/settings': typeof AuthSettingsRoute
  '/updates': typeof AuthUpdatesRoute
  '/': typeof AuthIndexRoute
  '/game/$platform/$slug': typeof AuthGamePlatformSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_auth/activity': typeof AuthActivityRoute
  '/_auth/discover': typeof AuthDiscoverRoute
  '/_auth/search': typeof AuthSearchRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/updates': typeof AuthUpdatesRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/game/$platform/$slug': typeof AuthGamePlatformSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/activity'
    | '/discover'
    | '/search'
    | '/settings'
    | '/updates'
    | '/game/$platform/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/setup'
    | '/activity'
    | '/discover'
    | '/search'
    | '/settings'
    | '/updates'
    | '/'
    | '/game/$platform/$slug'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/setup'
    | '/_auth/activity'
    | '/_auth/discover'
    | '/_auth/search'
    | '/_auth/settings'
    | '/_auth/updates'
    | '/_auth/'
    | '/_auth/game/$platform/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/updates': {
      id: '/_auth/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthUpdatesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/search': {
      id: '/_auth/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthSearchRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/discover': {
      id: '/_auth/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthDiscoverRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/activity': {
      id: '/_auth/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthActivityRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/game/$platform/$slug': {
      id: '/_auth/game/$platform/$slug'
      path: '/game/$platform/$slug'
      fullPath: '/game/$platform/$slug'
      preLoaderRoute: typeof AuthGamePlatformSlugRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthActivityRoute: typeof AuthActivityRoute
  AuthDiscoverRoute: typeof AuthDiscoverRoute
  AuthSearchRoute: typeof AuthSearchRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthUpdatesRoute: typeof AuthUpdatesRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthGamePlatformSlugRoute: typeof AuthGamePlatformSlugRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthActivityRoute: AuthActivityRoute,
  AuthDiscoverRoute: AuthDiscoverRoute,
  AuthSearchRoute: AuthSearchRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthUpdatesRoute: AuthUpdatesRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthGamePlatformSlugRoute: AuthGamePlatformSlugRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
