/**
 * Generate a Virtual File System module from the dist folder
 * This embeds all frontend assets into a TypeScript file that can be imported
 */

import { readdir, readFile, stat } from 'fs/promises';
import { join, relative } from 'path';

const DIST_DIR = './dist';
const OUTPUT_FILE = './src/server/generated/frontend-vfs.ts';

// Binary file extensions that need base64 encoding
const BINARY_EXTENSIONS = new Set([
  '.png', '.jpg', '.jpeg', '.gif', '.webp', '.ico', '.svg',
  '.woff', '.woff2', '.ttf', '.eot',
  '.webm', '.mp4', '.mp3', '.ogg',
  '.pdf', '.zip',
]);

async function getAllFiles(dir: string): Promise<string[]> {
  const files: string[] = [];

  async function walk(currentDir: string) {
    const entries = await readdir(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = join(currentDir, entry.name);

      if (entry.isDirectory()) {
        await walk(fullPath);
      } else if (entry.isFile()) {
        files.push(fullPath);
      }
    }
  }

  await walk(dir);
  return files;
}

function isBinaryFile(path: string): boolean {
  const ext = path.substring(path.lastIndexOf('.')).toLowerCase();
  return BINARY_EXTENSIONS.has(ext);
}

async function generateVFS() {
  console.log('📦 Generating Virtual File System from dist/...');

  // Check if dist exists
  try {
    await stat(DIST_DIR);
  } catch {
    console.error('❌ Error: dist/ folder not found. Run `bun run build:web` first.');
    process.exit(1);
  }

  const files = await getAllFiles(DIST_DIR);
  const vfsEntries: string[] = [];

  let totalSize = 0;

  for (const file of files) {
    const relativePath = relative(DIST_DIR, file).replace(/\\/g, '/');
    const content = await readFile(file);
    totalSize += content.length;

    if (isBinaryFile(file)) {
      // Base64 encode binary files
      const base64 = content.toString('base64');
      vfsEntries.push(`  '${relativePath}': '${base64}'`);
    } else {
      // Escape string content for text files
      const text = content.toString('utf-8');
      const escaped = text
        .replace(/\\/g, '\\\\')
        .replace(/'/g, "\\'")
        .replace(/\n/g, '\\n')
        .replace(/\r/g, '\\r')
        .replace(/\t/g, '\\t');
      vfsEntries.push(`  '${relativePath}': '${escaped}'`);
    }
  }

  const output = `// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by scripts/generate-vfs.ts
// Contains embedded frontend assets for single-binary deployment

export const frontendVFS: Record<string, string> = {
${vfsEntries.join(',\n')}
};

export const VFS_FILE_COUNT = ${files.length};
export const VFS_TOTAL_SIZE = ${totalSize};
`;

  // Ensure output directory exists
  const outputDir = OUTPUT_FILE.substring(0, OUTPUT_FILE.lastIndexOf('/'));
  await Bun.write(OUTPUT_FILE, output);

  console.log(`✅ Generated VFS with ${files.length} files (${(totalSize / 1024).toFixed(1)} KB)`);
  console.log(`   Output: ${OUTPUT_FILE}`);
}

generateVFS().catch(console.error);
